name: select_all_dropdown
description: select_all_dropdown is a highly customizable and user-friendly Flutter package that provides a multi-select dropdown with a convenient "Select All" feature. It allows users to select multiple items from a list with ease and efficiency, making it an ideal choice for forms, filtering options, and settings screens.
version: 0.1.1
homepage: https://www.linkedin.com/in/ashutosh-01-tiwari/
repository: https://github.com/Ashutosh980/select_all_dropdown

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  states_rebuilder: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
